import assert from 'node:assert/strict'
import test from 'node:test'
import { JSDOM } from 'jsdom'
import { readFileSync } from 'node:fs'
import createSidebarMotionClient from '../client/sidebar-motion.mjs'

function fixture(t) {
  const dom = new JSDOM('<!doctype html><html data-dsh-app-ui><head></head><body><div id="root"><div data-dsh-app-frame style="grid-template-columns: 280px minmax(400px, 1fr) minmax(0px, 600px); --dsh-app-overlay-tracks: previous; --dsh-app-chat-inset: 17px"><div data-dsh-center-col><header data-window-drag></header><div data-conversation-scroll><div data-chat-flow></div></div><div data-composer-seat></div></div><div data-shell-overlay><div data-sidebar-right-session="session"><div data-sidebar-right-panel="push" data-sidebar-right-open><div class="P3OORG_panelBody"><div><div data-dockkit-host="dock"><section data-dockkit-content="guide" data-dockkit-pane="pane"><div data-dockkit-strip></div><div><div class="P3OORG_tabBody"><section data-dsh-app-summary><input value="unsaved text"></section></div></div></section></div><div data-dockkit-host="float"><section data-dockkit-float="floating"></section></div></div></div></div></div></div></div></div></body></html>', { pretendToBeVisual: true })
  const original = Object.getOwnPropertyDescriptor(globalThis, 'document')
  Object.defineProperty(globalThis, 'document', { value: dom.window.document, configurable: true })
  const { document, window } = dom.window
  const frame = document.querySelector('[data-dsh-app-frame]')
  const panel = document.querySelector('[data-sidebar-right-panel]')
  let summaryWidth = 350, viewerWidth = 715
  panel.getBoundingClientRect = () => ({ width: panel.hasAttribute('data-dsh-app-panel-summary') ? summaryWidth : viewerWidth })
  const frames = new Map()
  let next = 0
  window.requestAnimationFrame = callback => { const id = ++next; frames.set(id, callback); return id }
  window.cancelAnimationFrame = id => frames.delete(id)
  const tick = async () => {
    await Promise.resolve()
    const pending = [...frames.values()]; frames.clear()
    for (const callback of pending) callback(0)
    await Promise.resolve()
  }
  let dispose
  createSidebarMotionClient().install({ effect: callback => { dispose = callback() } })
  t.after(() => { dispose?.(); dom.window.close(); if (original) Object.defineProperty(globalThis, 'document', original); else delete globalThis.document })
  return { document, window, frame, panel, tick, frames, resizePanel: (summary, viewer) => { summaryWidth = summary; viewerWidth = viewer }, dispose: () => { dispose?.(); dispose = undefined } }
}

test('resting summary keeps the full canvas and reserves only content inset through close', async t => {
  const f = fixture(t)
  const input = f.panel.querySelector('input')
  const nativeTracks = f.frame.style.gridTemplateColumns
  assert.ok(f.panel.hasAttribute('data-dsh-app-panel-summary'))
  assert.ok(f.frame.hasAttribute('data-dsh-app-right-summary'))
  assert.ok(f.frame.hasAttribute('data-dsh-app-right-overlay'))
  assert.equal(f.frame.style.getPropertyValue('--dsh-app-overlay-tracks'), '280px minmax(0px, 1fr) minmax(0px, 0px)')
  assert.equal(f.frame.style.getPropertyValue('--dsh-app-chat-inset'), '382px')
  assert.equal(f.frame.style.gridTemplateColumns, nativeTracks, 'native remains the writer of layout source geometry')
  f.panel.removeAttribute('data-sidebar-right-open')
  await f.tick()
  assert.equal(f.frame.hasAttribute('data-dsh-app-right-summary'), false)
  assert.ok(f.frame.hasAttribute('data-dsh-app-right-overlay'), 'closing does not briefly reinstate the native separate canvas track')
  assert.equal(f.frame.style.getPropertyValue('--dsh-app-chat-inset'), '0px')
  assert.ok(f.panel.hasAttribute('data-dsh-app-panel-summary'), 'closed summary retains its intrinsic card geometry for the exit')
  assert.equal(f.panel.querySelector('input'), input)
  assert.equal(input.value, 'unsaved text')
  assert.ok(f.document.querySelector('[data-dockkit-float]'), 'floats remain mounted under native ownership')
  f.dispose()
  assert.equal(f.frame.style.getPropertyValue('--dsh-app-overlay-tracks'), 'previous')
  assert.equal(f.frame.style.getPropertyValue('--dsh-app-chat-inset'), '17px')
  assert.equal(f.frame.hasAttribute('data-dsh-app-right-overlay'), false)
  assert.equal(f.panel.hasAttribute('data-dsh-app-panel-summary'), false)
  assert.equal(f.frame.hasAttribute('data-dsh-app-right-mode-changing'), false)
  assert.equal(f.frames.size, 0)
})

test('viewers and split panes reserve content inset on the shared canvas, while fullscreen needs no inset', async t => {
  const f = fixture(t)
  const host = f.panel.querySelector('[data-dockkit-host="dock"]')
  const summary = host.querySelector('[data-dsh-app-summary]')
  const viewer = host.cloneNode(true)
  viewer.querySelector('[data-dsh-app-summary]').removeAttribute('data-dsh-app-summary')
  viewer.querySelector('[data-dockkit-content]').setAttribute('data-dockkit-content', 'file')
  host.after(viewer)
  await f.tick()
  assert.equal(f.frame.hasAttribute('data-dsh-app-right-summary'), false)
  assert.equal(f.panel.hasAttribute('data-dsh-app-panel-summary'), false)
  assert.ok(f.frame.hasAttribute('data-dsh-app-right-overlay'))
  assert.equal(f.frame.style.getPropertyValue('--dsh-app-overlay-tracks'), '280px minmax(0px, 1fr) minmax(0px, 0px)')
  assert.equal(f.frame.style.getPropertyValue('--dsh-app-chat-inset'), '747px')
  assert.ok(f.frame.hasAttribute('data-dsh-app-right-mode-changing'), 'mode changes animate even when native expanded state does not change')
  viewer.hidden = true
  await f.tick()
  assert.ok(f.frame.hasAttribute('data-dsh-app-right-summary'))
  assert.equal(f.frame.style.getPropertyValue('--dsh-app-chat-inset'), '382px')
  f.panel.parentElement.style.cssText = 'position: relative; width: 0px'
  f.panel.style.cssText = 'width: 100vw; --dsh-sidebar-width: 100vw'
  f.panel.setAttribute('data-sidebar-right-panel', 'fullscreen')
  await f.tick()
  assert.equal(f.frame.hasAttribute('data-dsh-app-right-summary'), false)
  assert.ok(f.frame.hasAttribute('data-dsh-app-right-overlay'))
  assert.equal(f.frame.style.getPropertyValue('--dsh-app-chat-inset'), '0px')
  assert.equal(f.panel.querySelector('[data-dsh-app-summary]'), summary)
  assert.equal(f.panel.hasAttribute('aria-hidden'), false, 'native focus and accessibility state stay owned by the native panel')
})

test('retained inactive sessions cannot reserve summary geometry and app deactivation restores presentation', async t => {
  const f = fixture(t)
  const session = f.panel.parentElement
  session.hidden = true
  await f.tick()
  assert.equal(f.frame.hasAttribute('data-dsh-app-right-summary'), false)
  assert.equal(f.frame.hasAttribute('data-dsh-app-right-overlay'), false)
  assert.equal(f.frame.style.getPropertyValue('--dsh-app-chat-inset'), '0px')
  session.hidden = false
  await f.tick()
  assert.ok(f.frame.hasAttribute('data-dsh-app-right-summary'))
  f.document.documentElement.removeAttribute('data-dsh-app-ui')
  await f.tick()
  assert.equal(f.frame.hasAttribute('data-dsh-app-right-summary'), false)
  assert.equal(f.frame.style.getPropertyValue('--dsh-app-overlay-tracks'), 'previous')
  assert.equal(f.frame.style.getPropertyValue('--dsh-app-chat-inset'), '17px')
  assert.equal(f.panel.hasAttribute('data-dsh-app-panel-summary'), false)
  f.document.documentElement.setAttribute('data-dsh-app-ui', '')
  await f.tick()
  assert.ok(f.frame.hasAttribute('data-dsh-app-right-summary'))
})

test('resize updates only the content inset without writing header, scroll canvas or native pane geometry', async t => {
  const f = fixture(t)
  const untouched = [...f.document.querySelectorAll('[data-dsh-center-col], [data-window-drag], [data-conversation-scroll], [data-chat-flow], [data-composer-seat]')]
  const before = untouched.map(element => element.outerHTML)
  const nativeTracks = f.frame.style.gridTemplateColumns
  f.resizePanel(320, 640)
  f.window.dispatchEvent(new f.window.Event('resize'))
  assert.equal(f.frame.style.getPropertyValue('--dsh-app-chat-inset'), '352px')
  assert.equal(f.frame.style.gridTemplateColumns, nativeTracks)
  assert.deepEqual(untouched.map(element => element.outerHTML), before, 'content styling belongs to scoped root hooks, not a shrunken conversation shell')
  await f.tick(); await f.tick()
  f.panel.querySelector('[data-dsh-app-summary]').replaceWith(f.document.createElement('section'))
  await f.tick()
  assert.equal(f.frame.style.getPropertyValue('--dsh-app-chat-inset'), '672px')
  f.resizePanel(320, 580)
  f.panel.style.setProperty('--dsh-sidebar-width', '604px')
  await f.tick()
  assert.equal(f.frame.style.getPropertyValue('--dsh-app-chat-inset'), '612px', 'native panel width changes update the overlay inset independently of grid measurement')
})

test('viewport resize, native drag and instant session changes disable motion and dispose cleanly', async t => {
  const f = fixture(t)
  const html = f.document.documentElement
  f.window.dispatchEvent(new f.window.Event('resize'))
  assert.ok(html.hasAttribute('data-dsh-app-panel-resizing'))
  await f.tick()
  assert.ok(html.hasAttribute('data-dsh-app-panel-resizing'), 'keep snapping across the resize paint boundary')
  await f.tick()
  assert.equal(html.hasAttribute('data-dsh-app-panel-resizing'), false)
  f.frame.setAttribute('data-rightbar-instant', '')
  await f.tick()
  assert.equal(html.hasAttribute('data-dsh-app-panels-instant'), false, 'native instant state is read directly by CSS, without a delayed HTML mirror')
  f.frame.removeAttribute('data-rightbar-instant')
  f.frame.setAttribute('data-dragging', '')
  await f.tick()
  assert.ok(f.frame.hasAttribute('data-dragging'), 'native drag state remains under native ownership')
  f.frame.removeAttribute('data-dragging')
  await f.tick()
  assert.equal(html.hasAttribute('data-dsh-app-panels-instant'), false)
  f.window.dispatchEvent(new f.window.Event('resize'))
  f.dispose()
  assert.equal(html.hasAttribute('data-dsh-app-panel-resizing'), false)
  assert.equal(html.hasAttribute('data-dsh-app-panels-instant'), false)
  assert.equal(f.frames.size, 0)
})

test('instant mode exit releases motion synchronously before a native collapse paints', async t => {
  const f = fixture(t)
  const style = f.document.createElement('style')
  style.textContent = readFileSync(new URL('../client/sidebar-workbench.css', import.meta.url), 'utf8')
  f.document.head.append(style)
  const rules = [...style.sheet.cssRules].filter(rule => rule.selectorText)
  const nativeGuard = rules.find(rule => rule.selectorText.includes('[data-dsh-app-frame]:is([data-rightbar-instant], [data-dragging])') && rule.selectorText.includes('[data-dockkit-host="dock"]'))
  assert.ok(nativeGuard)
  const host = f.panel.querySelector('[data-dockkit-host="dock"]')
  f.frame.setAttribute('data-rightbar-instant', '')
  await f.tick()
  assert.ok(host.matches(nativeGuard.selectorText))
  f.frame.removeAttribute('data-rightbar-instant')
  f.panel.removeAttribute('data-sidebar-right-open')
  assert.equal(host.matches(nativeGuard.selectorText), false, 'the transition guard releases in the same commit, before observer scheduling')
  assert.equal(f.document.documentElement.hasAttribute('data-dsh-app-panels-instant'), false)
  assert.equal(style.textContent.includes('data-dsh-app-panels-instant'), false, 'a stale mirror cannot disable a later open or close')
  await f.tick()
})

test('late panels and replacement shells are discovered while streamed chat does not schedule layout work', async t => {
  const f = fixture(t)
  await f.tick()
  f.panel.remove()
  await f.tick()
  assert.equal(f.panel.hasAttribute('data-dsh-app-panel-summary'), false)
  const next = f.panel.cloneNode(true)
  f.document.querySelector('[data-sidebar-right-session]').append(next)
  await f.tick()
  assert.ok(next.hasAttribute('data-dsh-app-panel-summary'))
  await f.tick()
  const replacement = f.frame.cloneNode(true)
  replacement.style.setProperty('--dsh-app-overlay-tracks', 'replacement')
  f.frame.replaceWith(replacement)
  await f.tick()
  assert.ok(replacement.hasAttribute('data-dsh-app-right-summary'))
  assert.equal(f.frame.style.getPropertyValue('--dsh-app-overlay-tracks'), 'previous')
  await f.tick()
  f.frame.setAttribute('data-rightbar-instant', '')
  await Promise.resolve()
  assert.equal(f.frames.size, 0, 'a removed frame no longer owns layout observers')
  const message = f.document.createElement('p')
  message.textContent = 'Streaming message'
  replacement.querySelector('[data-dsh-center-col]').append(message)
  await Promise.resolve()
  assert.equal(f.frames.size, 0)
  message.firstChild.textContent += ' text'
  await Promise.resolve()
  assert.equal(f.frames.size, 0)
  const syntaxSpan = f.document.createElement('span')
  replacement.querySelector('[data-dsh-app-summary]').append(syntaxSpan)
  await Promise.resolve()
  syntaxSpan.style.color = 'red'
  await Promise.resolve()
  assert.equal(f.frames.size, 0, 'streamed syntax/editor style changes do not schedule pane geometry')
  f.dispose()
  assert.equal(replacement.style.getPropertyValue('--dsh-app-overlay-tracks'), 'replacement')
})

test('motion stylesheet slides the actual dock and delays only exit visibility, leaving floats independent', t => {
  const f = fixture(t)
  const style = f.document.createElement('style')
  style.textContent = readFileSync(new URL('../client/sidebar-workbench.css', import.meta.url), 'utf8')
  f.document.head.append(style)
  assert.ok(style.sheet.cssRules.length > 0, 'the complete owned stylesheet parses')
  const rules = [...style.sheet.cssRules].filter(rule => rule.selectorText)
  const nativeExit = rules.find(rule => rule.selectorText.includes('[data-sidebar-right-panel]') && rule.selectorText.includes('[data-dockkit-host="dock"]') && !rule.selectorText.includes('[data-sidebar-right-open]') && rule.style.transition?.includes('visibility'))
  assert.ok(nativeExit, 'the actual native dock slides instead of animating a duplicated panel')
  assert.ok(nativeExit.style.transition.includes('visibility 0s linear var(--dsh-workbench-motion-duration)'), 'exit stays visible until its slide completes')
  const nativeEnter = rules.find(rule => rule.selectorText.includes('[data-sidebar-right-open]') && rule.style.transition?.includes('visibility'))
  assert.ok(nativeEnter.style.transition.endsWith('visibility 0s'), 'opening never waits behind an old exit visibility delay')
  assert.equal(f.document.querySelector('[data-dockkit-host="float"]').matches(nativeExit.selectorText), false)
  const frameMotion = rules.find(rule => rule.selectorText.split(',').some(selector => selector.trim() === 'html[data-dsh-app-ui] [data-dsh-app-frame]') && rule.style.transition?.includes('grid-template-columns'))
  assert.ok(frameMotion, 'native left-sidebar changes can still animate the shared canvas grid')
  const canvas = rules.find(rule => rule.selectorText === 'html[data-dsh-app-ui] [data-dsh-app-frame][data-dsh-app-right-overlay]')
  assert.equal(canvas.style.getPropertyValue('grid-template-columns'), 'var(--dsh-app-overlay-tracks, 0px minmax(0px, 1fr) minmax(0px, 0px))')
  assert.ok(style.textContent.includes('grid-template-columns: var(--dsh-app-overlay-tracks, 0px minmax(0px, 1fr) minmax(0px, 0px)) !important;'), 'shared canvas overrides the native inline track source')
  const collapsedCanvas = rules.find(rule => rule.selectorText.includes('[data-dsh-app-right-overlay][data-sidebar-collapsed]'))
  assert.equal(collapsedCanvas.style.getPropertyValue('grid-template-columns'), '0px minmax(0px, 1fr) minmax(0px, 0px)')
  const viewerResize = rules.find(rule => rule.selectorText.includes('[data-dsh-app-right-overlay]:not([data-dsh-app-right-summary]) > [data-side="rightbar"]') && rule.style.left)
  assert.equal(viewerResize.style.left, 'calc(100% - var(--dsh-app-chat-inset, 0px) + 20px)')
  assert.equal(viewerResize.style.top, '62px')
  assert.equal(viewerResize.style.bottom, '12px')
  f.frame.setAttribute('data-dsh-app-right-summary', '')
  const resize = f.document.createElement('div')
  resize.setAttribute('data-side', 'rightbar')
  f.frame.append(resize)
  assert.equal(resize.matches(viewerResize.selectorText), false, 'the summary keeps its native resize handle hidden')
  f.frame.removeAttribute('data-dsh-app-right-summary')
  assert.ok(resize.matches(viewerResize.selectorText), 'only the visible viewer handle follows its card edge')
  assert.equal(resize.hasAttribute('style'), false, 'native pointer capture and inline/store geometry remain untouched')
  for (const element of f.document.querySelectorAll('[data-dsh-center-col], [data-window-drag], [data-conversation-scroll]')) {
    assert.equal(element.matches(canvas.selectorText), false, 'the full canvas/header/scroll region are never targeted as a narrower content column')
  }
  const compact = rules.find(rule => rule.selectorText.includes('[data-dsh-app-panel-summary]') && rule.style.width)
  assert.equal(compact.style.width, 'var(--dsh-workbench-summary-width)')
  assert.equal(compact.style.bottom, 'auto')
  const push = rules.find(rule => rule.selectorText === 'html[data-dsh-app-ui] [data-sidebar-right-panel="push"]')
  assert.equal(push.style.top, '62px', 'floating push viewers leave the full conversation header and its top-right controls usable')
  assert.equal(style.textContent.includes('data-dsh-bottom-panel'), false, 'removed bottom workbench has no presentation lifecycle')
  const fullscreen = rules.find(rule => rule.selectorText.includes('[data-sidebar-right-panel="fullscreen"]') && rule.style.width)
  assert.equal(fullscreen.style.width, 'calc(var(--dsh-sidebar-width) - var(--dsh-app-rail-width, 0px) - 34px)')
  assert.equal(fullscreen.style.getPropertyValue('max-width'), 'calc(100vw - var(--dsh-app-rail-width, 0px) - 34px)', 'zero-width native fullscreen host cannot collapse its viewport-sized pane')
  const narrow = [...style.sheet.cssRules].findLast(rule => rule.conditionText === '(max-width: 767px)')
  const narrowPane = [...narrow.cssRules].find(rule => rule.selectorText.endsWith('[data-sidebar-right-panel]'))
  assert.equal(narrowPane.style.getPropertyValue('max-width'), 'calc(100vw - var(--dsh-app-rail-width, 0px) - 26px)')
  assert.ok(rules.filter(rule => rule.selectorText.includes('[data-sidebar-right-panel]') || rule.selectorText.includes('[data-sidebar-right-panel="fullscreen"]') || rule.selectorText.includes('[data-dsh-app-panel-summary]')).every(rule => !rule.style.width?.includes('%') && !rule.style.getPropertyValue('max-width')?.includes('%')), 'docked card dimensions stay stable while their native grid track collapses')
  const reduced = [...style.sheet.cssRules].findLast(rule => rule.conditionText === '(prefers-reduced-motion: reduce)')
  assert.ok([...reduced.cssRules].some(rule => rule.style.getPropertyValue('transition') === 'none' && rule.style.getPropertyPriority('transition') === 'important'))
})
